### ISSUE TITLE
rustybuzz deprecation

### ISSUE THREAD

**Issue by jackpot51** [pop-os/cosmic-text#172]
Rustybuzz has been marked as deprecated: https://github.com/RazrFalcon/rustybuzz/issues/74

At this time my plan is to fork rustybuzz into a module in cosmic-text, unless one of two things happen:

1. It can be demonstrated that swash shaping can be integrated into cosmic-text and passes the universal declaration of human rights translations test. To clarify my comment on the issue, as I understand it, swash shaping is not as feature complete as rustybuzz and a regression in capabilities would not be acceptable for cosmic-text

2. rustybuzz can be moved to an organization that has similar goals to cosmic-text: high accuracy, and a gradual movement towards higher performance (while preserving accuracy). As I commented, I foresee this requiring a split from the current API that is somewhat inherited from harfbuzz, which means backporting changes from harfbuzz would be harder.

**Comment by jackpot51** [comment]
A third option is to use harfbuzz directly.

**Comment by jackpot51** [comment]
This is indeed a big issue @grovesNL. There is more talk about this on that rustybuzz issue. My hope is that I can maintain no_std and wasm support indefinitely, regardless of what happens.

**Comment by coderedart** [comment]
`harfbuzz` would work fine with `wue` (wasm32-unknown-emscripten). 

But the real problem is `wasm_bindgen` and `wuu` (wasm32-unknown-unknown) which is slowly worked on -> https://github.com/rustwasm/wasm-bindgen/issues/3454

**Comment by MarcGuiselin** [comment]
Hello everyone, I'm new here!

As much as I love rust, I believe having feature-complete (and thus critically more accessible) text shaping is more important.

Having the ability to use harfbuzz with cosmic-text (probably using a feature flag) is IMO the only correct solution moving forward, because as RazrFalcon explains it's simply not sustainable to maintain rustybuzz without any backing. So as time goes on, we'll only see more issues crop up unless someone takes up the mantle.

Rustybuzz should serve as a fallback on wasm targets until https://github.com/rustwasm/wasm-bindgen/issues/3454 is addressed (and any other cross-compilation issues). Additionally, in browser environments it always remains possible to use the browser's own text editing support.

None of this is ideal, but at least provides a workable path forward that leaves plenty of room for improvements in the future.

**Comment by grovesNL** [comment]
@MarcGuiselin I target both native and WebAssembly and wouldn't want to include harfbuzz (even if it was technically possible to use a common ABI) because of the extra size and complexity of including a C++ toolchain. I also can't use the browser's built-in shaping for WebAssembly.

**Comment by DemiMarie** [comment]
@MarcGuiselin In certain environments (notably [Qubes OS](https://www.qubes-os.org) and probably [SpectrumOS](https://www.spectrum-os.org) as well), harfbuzz is not acceptable because of security concerns.  I’d like to use COSMIC Text to allow rendering arbitrary text in privilege contexts in Qubes OS, but that is only okay if it remains a purely safe Rust library.

**Comment by DemiMarie** [comment]
@jackpot51 to elaborate on the security concerns: Qubes OS has users (such as Edward Snowden!) who malicious actors might well be willing to burn zero-day exploits on.  A zero-day in Harfbuzz that can be triggered purely through malicious text to be rendered (as opposed to requiring a malicious font) is not something I have been able to exclude.
