### ISSUE TITLE
Request: Allow buffer dimensions to be undefined

### ISSUE THREAD

**Issue by nicoburns** [pop-os/cosmic-text#42]
Currently you have to set the Buffer dimensions before shaping. But it is common requirement to size a box containing some text based on the size of the text itself. It would therefore be great if it were possible to shape/layout with one or both dimensions being unset/infinite (it should be possible to independently set each dimension to infinite).

This could be represented with an `Option<i32>` (or `Option<u32>` - does a negative buffer size make sense?) or possibly just an `f32`, making use of the floating point `Infinity` value.

**Comment by jackpot51** [comment]
Using the maximum value for size essentially does this, unless you have text that will be more than billions of pixels wide

**Comment by dhardy** [comment]
If the goal is simply to measure the text's width for UI layout purposes, then (1) there will be some maximum width above which the exact result doesn't matter (because wrapping will be needed) and (2) layout of any remaining text is irrelevant.

Consider adding a method especially for this purpose: https://docs.rs/kas-text/latest/kas_text/struct.TextDisplay.html#method.measure_width

**Comment by nicoburns** [comment]
> If the goal is simply to measure the text's width for UI layout purposes

This is basically the use case, except:

- Sometimes there is no limit (but this can be emulated by just setting a very high limit)
- I often want to know the height as well as the width. Although it's true that separate methods for "just height", "just width" and "both" might be a good idea (note that in the case of vertical text it might be height that's cheaper to compute)
- The "unlimited width" (never wrap) and "zero width" (always wrap) cases are common and should potentially have an optimised implementation (and/or be computed together and cached) if such an implementation would be meaningfully cheaper.

**Comment by dhardy** [comment]
Height can only be determined after wrapping (hence you must do full layout and automatically get both). *Maybe* some opts are available if you only want height (e.g. not re-ordering lines), but I doubt there's much value. I assumed #70 is about this.

I ended up using a GUI layout algorithm which fully determines width before considering height, hence the two-step approach works for me, but I am well aware that most layout algorithms address both simultaneously.

Calculating only height without ever wrapping is as simple as multiplying the line height by the number of lines and adding in line-gaps (not sure if Cosmic-text uses these?), assuming your font size is constant and there are no oversize glyphs, [subscript / superscript](https://en.wikipedia.org/wiki/Subscript_and_superscript), etc.

Not sure why you'd want to measure height with "zero width". If words are too long for a line, there is hyphenation and even per-glyph breaking. You might as well just assume the maximum height is some BIG NUMBER (or screen height), at which point it doesn't help with layout.

**Comment by nicoburns** [comment]
> Height can only be determined after wrapping (hence you must do full layout and automatically get both).

Presumably for vertical text this is reversed and it's width that can only be determined by doing a full layout? (I'd be interested to to know if/how your GPU layout algorithm works for vertical text).

I think what I want is a way to do "full layout" but without storing the result except for the overall width/height. Which should mean that no allocations need to take place unlike what I'm imagining happens in a regular layout where the contents of each line are stored.

> Not sure why you'd want to measure height with "zero width". If words are too long for a line, there is hyphenation and even per-glyph breaking.

CSS layout uses this to determine a minimum width for text nodes (under specified line-breaking rules which by default do not permit hyphenation or per-glyph breaking)

> Calculating only height without ever wrapping is as simple as multiplying the line height by the number of lines and adding in line-gaps (not sure if Cosmic-text uses these?), assuming your font size is constant and there are no oversize glyphs, [subscript / superscript](https://en.wikipedia.org/wiki/Subscript_and_superscript), etc.

I think I'd usually want the height taking into account all these edge cases.

**Comment by Imberflur** [comment]
> If the goal is simply to measure the text's width for UI layout purposes, then (1) there will be some maximum width above which the exact result doesn't matter (because wrapping will be needed) and (2) layout of any remaining text is irrelevant.

I did not see this mentioned, but I'm fairly certain there are some scenarios where layout needs to continue after wrapping to determine the exact width. I.e. if the UI layout algorithm needs the minimum width that the text will fit in, it is useful to continue since wrapped text won't necessarily be as wide as the width limit that forced it to wrap.

For instance, consider text consisting of just two words that slightly exceed the width limit such that the second word will be placed on a new line. In this case, the difference between the width of the wrapped text (which is the width of the larger word) and the width used as a limit can be quite significant.

I can see how the difference would be negligible when there are many lines of wrapped text (so there is likely a line that almost fills the space) or the width limit is relatively large compared to typical words. So in scenarios like these or where UI layouting doesn't actually need the minimum width, it seems like skipping further layout work can be quite useful.

It might be interesting to have UI layout code that heuristically switches to the more efficient method when processing large pieces of text or to have a way to short-circuit width measurement if it reaches a certain threshold after wrapping is accounted for :thinking:

**Comment by Imberflur** [comment]
I've written up a pseudo-RFC with a potential API for measurement (where using `f32::MAX` will always work) as well as reusing work between measurement and final layout.
<https://gist.github.com/Imberflur/e4ad4f878816e602ef57ea35d529ae17>

I think it is rough in some respects and could benefit from examination, input, and alternative ideas. Especially, wrt the "awkward workflow" drawback and the unresolved question.

**Comment by jackpot51** [comment]
This will be handled in #70.
