### ISSUE TITLE
Allow access to &mut Database from FontSystem

### ISSUE THREAD

**Issue by notgull** [pop-os/cosmic-text#75]
I'd like to be able to access the underlying `Database` in a `FontSystem` mutably, so I can easily add fonts without needing to convert to the underlying `Database` and back.

However, the `Database` is currently self-referentially borrowed for caching the font-ID-to-font relationship. It looks like this is due to the font lookup in `fontdb` being an `O(n)` process. RazrFalcon/fontdb#47 would fix that problem and allow us to solve this issue.

**Comment by dhardy** [comment]
The approach in #89 was slow.

Alternative: allocate all fonts in a `Box<..>` so that they never move / deallocate, then cast references to `&'static`. Store the database in a global static with methods allowing new fonts be added only.

I'm not going to write a PR, but you could probably copy a lot of [my code](https://github.com/kas-gui/kas-text/blob/master/src/fonts/library.rs) since I already wrote a very similar library.

API: https://docs.rs/kas-text/latest/kas_text/fonts/struct.FontLibrary.html

Bonus feature: the library supports a [default font](https://docs.rs/kas-text/latest/kas_text/fonts/index.html#fontid-and-the-default-font) so that simple `Text` objects can be constructed without access to the font library.
